version: '3.1'
services:
  alice:
    build: containers/alice
    networks:
      attacknet:
        ipv4_address: 10.0.1.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./data:/data
  bob:
    build: containers/bob
    networks:
      attacknet:
        ipv4_address: 10.0.1.3
    cap_add:
    - NET_ADMIN
  eve:
    build: containers/eve
    command: tcpdump -i eth0 -U -w /data/eve.pcap
    volumes:
    - ./data:/data
    networks:
      attacknet:
        ipv4_address: 10.0.1.4
    privileged: true
networks:
  attacknet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
